import {
  AddIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  CardIcon,
  DeleteIcon,
  DoneIcon,
  DownIcon,
  EditIcon,
  ErrorIcon,
  HomeIcon,
  ImageIcon,
  LeftIcon,
  OrdersIcon,
  PackingIcon,
  PlaneIcon,
  RemoveIcon,
  RightIcon,
  SearchIcon,
  UpLoadIcon,
  UpIcon,
  LogoIcon,
  AddIconWhite,
  ArrowLeftIconWhite,
  ArrowRightIconWhite,
  CardIconWhite,
  DeleteIconWhite,
  DoneIconWhite,
  DownIconWhite,
  EditIconWhite,
  ErrorIconWhite,
  HomeIconWhite,
  ImageIconWhite,
  LeftIconWhite,
  OrdersIconWhite,
  PackingIconWhite,
  PlaneIconWhite,
  RemoveIconWhite,
  RightIconWhite,
  SearchIconWhite,
  UpLoadIconWhite,
  UpIconWhite,
  LogoIconWhite,
  ArrowRightIconRed
} from '../../../assets/icons/index.js';

export const ICONS = {
  add: AddIcon,
  arrowleft: ArrowLeftIcon,
  arrowright: ArrowRightIcon,
  card: CardIcon,
  delete: DeleteIcon,
  done: DoneIcon,
  down: DownIcon,
  edit: EditIcon,
  error: ErrorIcon,
  home: HomeIcon,
  image: ImageIcon,
  left: LeftIcon,
  orders: OrdersIcon,
  packing: PackingIcon,
  plane: PlaneIcon,
  remove: RemoveIcon,
  right: RightIcon,
  search: SearchIcon,
  upload: UpLoadIcon,
  up: UpIcon,
  logo: LogoIcon,
  add_white: AddIconWhite,
  arrowleft_white: ArrowLeftIconWhite,
  arrowright_white: ArrowRightIconWhite,
  card_white: CardIconWhite,
  delete_white: DeleteIconWhite,
  done_white: DoneIconWhite,
  down_white: DownIconWhite,
  edit_white: EditIconWhite,
  error_white: ErrorIconWhite,
  home_white: HomeIconWhite,
  image_white: ImageIconWhite,
  left_white: LeftIconWhite,
  orders_white: OrdersIconWhite,
  packing_white: PackingIconWhite,
  plane_white: PlaneIconWhite,
  remove_white: RemoveIconWhite,
  right_white: RightIconWhite,
  search_white: SearchIconWhite,
  upload_white: UpLoadIconWhite,
  up_white: UpIconWhite,
  logo_white: LogoIconWhite,
  arrowright_red: ArrowRightIconRed,
};
