import { OrderDetailsModalProvider } from './contexts/OrderDetailsModalContext';
import { LoadingProvider } from './contexts/LoadingContext';
import { OrderDetailsModal } from './components/ui/organisms/orderDetailsModal/orderDetailsModal';
import { GlobalSpinner } from './components/ui/organisms';

import './global.css';

export const metadata = {
  title: 'Welcome to ',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <OrderDetailsModalProvider>
          <LoadingProvider>
            {children}
            <GlobalSpinner />
            <OrderDetailsModal />
          </LoadingProvider>
        </OrderDetailsModalProvider>
      </body>
    </html>
  );
}
