import { OrderDetailsModalProvider } from './contexts/OrderDetailsModalContext';
import { LoadingProvider } from './contexts/LoadingContext';
import { NotificationProvider } from './contexts/NotificationContext';
import { SessionProvider } from './contexts/SessionContext';
import { GlobalSpinner, OrderDetailsModal, NotificationModal } from './components/ui/organisms';

import './global.css';

export const metadata = {
  title: 'Welcome to ',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NotificationProvider>  
          <OrderDetailsModalProvider>
            <LoadingProvider>
              <SessionProvider>
                <GlobalSpinner />
                <OrderDetailsModal />
                <NotificationModal />
                {children}
              </SessionProvider>
            </LoadingProvider>
          </OrderDetailsModalProvider>
        </NotificationProvider>
      </body>
    </html>
  );
}
