import './global.css';

import { LoadingProvider } from './contexts/LoadingContext';
import { GlobalSpinner } from './components/ui/organisms';

export const metadata = {
  title: 'Welcome to ',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <LoadingProvider>
          {children}
          <GlobalSpinner />
        </LoadingProvider>
      </body>
    </html>
  );
}
